### ISSUE TITLE
Unexpected token '='

### ISSUE THREAD

**Issue by ghost** [wzbg/base58check#3]
Getting:

```
node bs.js 
/home/user/tests/node_modules/base58check/index.js:13
module.exports.encode = (data, prefix = '00', encoding = 'hex') => {
                                      ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/tests/scripts/bs.js:1:72)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

While executing:

```
var bs = require('base58check');

const data = '086eaa677895f92d4a6c5ef740c168932b5e3f44';
console.log(bs.encode(data));

console.log(bs.decode(bs.encode(data)));
```

On node v4.6.1

**Comment by Voelundr** [comment]
If someone is also running into this error change index.js
Before:
> module.exports.encode = (data, prefix = '00', encoding = 'hex') => {

After:
> var prefix = '00'
module.exports.encode = (data) => {
const encoding = 'hex'
